### ISSUE TITLE
Discussion / Discord?

### ISSUE THREAD

**Issue by Reebz** [timhul/ClassicSim#104]
Seeking a place to discuss sim results and rotation recommendations. There are some issue reports I don’t agree with but without deeper discussion and analysis of real world logging it’s hard to make adjustments. 

Does a forum or discord exist in support of this project?

**Comment by timhul** [comment]
No, but I agree with you that there is definitely a need for it. Discord is probably the best bet.

**Comment by pmb123** [comment]
Shall we make one?

**Comment by timhul** [comment]
https://discord.gg/NGVwKVK
