### ISSUE TITLE
Unstable MAX DPS Simulation

### ISSUE THREAD

**Issue by 01Lanz** [timhul/ClassicSim#109]
I ran 250K iterations and 1M iterations. On both occasions, the MAX DPS went wild. Unfortunately I do not know what may have happened.

I took the liberty to upload a screenshot of it.

Statistics _ Distribution
https://ibb.co/ZYprxfY

Settings
https://ibb.co/1LrQT02

**Comment by veluria** [comment]
Are you using the latest build with the fix for #84?

**Comment by 01Lanz** [comment]
Yes, I downloaded the file from 05-Jan-2020
