### ISSUE TITLE
Maybe a stupid question regarding compiling 

### ISSUE THREAD

**Issue by Comodooo** [timhul/ClassicSim#113]
Lovely tool, so thanks so much for it. 

Just a question, is it possible to compile this with VS or do you need to do it with QT? Would love to try this out with the other classes also except for only warriors that the precompiled release is using.

BR

**Comment by timhul** [comment]
> Lovely tool, so thanks so much for it.
> 
> Just a question, is it possible to compile this with VS or do you need to do it with QT? 

With enough configuration yes. You'll need to include the QT libs on the lib path so QT has to be installed locally. There are probably a bunch of other flags that have to be passed as well I'm sure, I'd need to take a good look at it to say for sure. My advice is that if you are not knowledgable about the requirements for custom C++ compilation environments you should consider using the QT built-in instead.

> Would love to try this out with the other classes also except for only warriors that the precompiled release is using.
> 
> BR

Maybe I'm misunderstanding you but you can switch classes in the GUI. Are you saying you can't switch from Warrior to other classes? Note that Priest and Warlocks are not available yet.

**Comment by Comodooo** [comment]
Hi @timhul 

Thanks for your reply, ok I will keep trying with build my own compilation environment, seems like a fun project at least :) 

And regarding that I could only watch one class...... for some reason it didn't work right clicking on the different classes yesterday, but after re-downloading the executable again it seems to be working.

Is there a possibility to enlarge the different profiles so that I could maybe have 8 of each instead of 3?

**Comment by timhul** [comment]
> Is there a possibility to enlarge the different profiles so that I could maybe have 8 of each instead of 3?

Yes but it requires changes to the places where you want to support more choices, recompilation, and GUI changes to be able to select those indices.

**Comment by timhul** [comment]
Closing this as I consider the question answered. Good luck!
