### ISSUE TITLE
Cannot compile due to: call of overloaded ‘append(<brace-enclosed initializer list>)’ is ambiguous

### ISSUE THREAD

**Issue by veluria** [timhul/ClassicSim#121]
ClassicSim/Class/Common/GeneralBuffs.cpp:43: error: call of overloaded ‘append(<brace-enclosed initializer list>)’ is ambiguous
       43 |     mutex_buff_groups.append({"Flask of Supreme Power", "Flask of Distilled Wisdom"});

See also: https://stackoverflow.com/questions/14587436/call-of-overloaded-brace-enclosed-initializer-list-is-ambiguous-how-to-deal-w

My environment: 

    gcc 9.2.0
    qt 5.14.0
    linux 5.5

I'm not sure how to fix it – or more specifically, how you want it to be fixed.

**Comment by jluiken** [comment]
"how you want it to be fixed" Wow....

Read the developer information wiki. Not precisely sure what you are doing wrong / aren't doing right, but I have no problems compiling with Qt 5.11.3.

**Comment by veluria** [comment]
What in my report does warrant such a rude reply? Prior to Qt 5.14, everything worked just fine for me. Simply raising an issue here that others might encounter in the future. If you cannot contribute anything to this issue, just don't comment. Thanks.

**Comment by jluiken** [comment]
Reading is hard.

"Qt Creator with mingw 5.3.0 and Qt 5.11.0 - Qt 5.11.3 (in Qt installer, make sure to include archived releases). Note that Qt 5.12.0+ / mingw 5.7+ does not seem to work (on Win 10 x64 at least). MVSC15-19 has also so far been unsuccessful."

**Comment by timhul** [comment]
@jluiken I think I'd prefer it like this:

`mutex_buff_groups.append(QSet<QString>({"Flask of Supreme Power", "Flask of Distilled Wisdom"}));`

That is, specify the constructor to use.
