### ISSUE TITLE
Use max rank Trueshot Aura

### ISSUE THREAD

**Issue by valepu** [timhul/ClassicSim#128]
Hello, 
Today when running some simulations i realized that When i get the Trueshot Aura talent as a hunter my AP increases by 50 rather than 100 (at least in the equipment tab), it looks like rank 1 of TS aura  ( https://classic.wowhead.com/spell=19506/trueshot-aura ) is being used rather than the last rank ( https://classic.wowhead.com/spell=20906/trueshot-aura )

I'm not sure if this is only visual or it affects the simulation too

**Comment by timhul** [comment]
It does use R1! Fixed in 6edfab63a49fe0b939f16cdb058024bc44d8f51c.

Thanks for the report.
