### ISSUE TITLE
Cannot customize rotation files in latest version (02.05.2020 release)

### ISSUE THREAD

**Issue by IsaacSmith13** [timhul/ClassicSim#129]
It appears as though there is a test running every time the program launches to ensure the rotation files are as expected, but this means that if you make any changes to them the program no longer launches. Here is the errror: 
![image](https://user-images.githubusercontent.com/47432804/74085913-0c25df80-4a4c-11ea-84af-a56c13bb853b.png)

And this is the minimum I have to change before it breaks:

|||
|---|---|
|Before|After|
|![image](https://user-images.githubusercontent.com/47432804/74085955-763e8480-4a4c-11ea-9158-15f358746dd7.png)|![image](https://user-images.githubusercontent.com/47432804/74085964-8bb3ae80-4a4c-11ea-97b5-d50006dcf655.png)|

Is it possible to assert against fake test files or strings of "pre-read data" rather than the actual files?

NOTE: This error is new to this release, as I had the last release and my rotation files were modified successfully.

**Comment by timhul** [comment]
The tests were accidentally included in the 2020 02 05 release, just created a 2020 02 10 release that does not have tests enabled.

Thanks for the heads up!
