### ISSUE TITLE
Add 1H enchants to 2H weapons

### ISSUE THREAD

**Issue by Haplix92** [timhul/ClassicSim#130]
Phase 3 of WoW Classic introduces the 'Enchant Weapon - Agility' (i.e. +15 Agi) enchant.  This will be the best enchant for hunters, even to 2H weapons, until Phase 5.  

The 'Enchant 2H Weapon - Agility' (i.e. +25 agi) enchant doesn't come out until Phase 5.

Please allow selection of the 'Enchant Weapon - Agility' (i.e. +15 Agi) enchant for 2H weapons.

**Comment by Haplix92** [comment]
I just downloaded the latest version and it appears you already added the 'Enchant Weapon - Agility' (i.e. +15 Agi) enchant as an option for 1H weapons.

It does appear the 'Enchant 2H Weapon - Agility' (i.e. +25 agi) enchant is no longer available, even for Phase 5 which is when it will be available.

**Comment by timhul** [comment]
I've made 1h agi possible to be selected for 2h in 40331b480c387aac1a162d81297431d6a698cc01. I am unable to replicate what you describe about missing 2h Agi for hunters, are you sure you had a 2h equipped?

**Comment by Haplix92** [comment]
It's working now.  Maybe I did have a 1H equipped.
