### ISSUE TITLE
Add the 'Enchant Chest - Stats' (i.e. +3 to all stats) enchant

### ISSUE THREAD

**Issue by Haplix92** [timhul/ClassicSim#131]
Please add the 'Enchant Chest - Stats' (i.e. +3 to all stats) enchant.  

The 'Enchant Chest - Greater Stats' (i.e. +4 to all stats) enchant hasn't dropped on all servers and isn't necessarily available.

**Comment by timhul** [comment]
Added in ae8693ddcd44722a331701c3d817594e21d78bf3.

Thanks for your report.
