### ISSUE TITLE
Ebon Hand is marked as Main Hand, but is One Hand

### ISSUE THREAD

**Issue by wlfbck** [timhul/ClassicSim#147]
Title. And thus not available when you click on the off hand and waht to select it.

**Comment by timhul** [comment]
This was fixed in https://github.com/timhul/ClassicSim/commit/8e9a0b9de8884d3ea1df3b10b6b536f6903d8007 and will be released soon. Thanks for your report!

**Comment by timhul** [comment]
I've now created the release (2020-02-19-1) with this fix in it.
