### ISSUE TITLE
Damage of Thunderfury

### ISSUE THREAD

**Issue by luhao007** [timhul/ClassicSim#151]
Currently in the simulation, the damage of Thunderfury's effect is simulated at 16-29. It should be 300.

**Comment by timhul** [comment]
What you are seeing is the bonus base damage from nature damage, which is modelled as a 100% proc rate nature effect. This part is intended.

But it does seem that the 300 damage proc no longer is proccing. Fixed in 8a2cb9515a57b772a47420b62e2c3e3f2c287cf7.
