### ISSUE TITLE
Expose Weakness (Hunter t2 proc) is 10x the actual proc chance

### ISSUE THREAD

**Issue by IsaacSmith13** [timhul/ClassicSim#155]
Here is a log of someone attacking essentially a target dummy for 26 minutes:
https://www.warcraftlogs.com/reports/rx31nd7AfgPL6bkz/#fight=last&type=auras&spells=debuffs&hostility=1&ability=23577

You can see the buff only has a 5% uptime; when I sim myself in full t2 it shows a 50% uptime. The proc change just needs divided by ten.

**Comment by timhul** [comment]
Not the biggest of sample sizes, but it is obviously very probable that the proc rate should be reduced a fair bit.

**Comment by timhul** [comment]
Fixed with PR #157
