### ISSUE TITLE
[Boss Mechanics] Vaelestrasz buff not returning energy

### ISSUE THREAD

**Issue by jluiken** [timhul/ClassicSim#156]
Hi Tim,

When performing a simulation in Vaelestrasz mode, it shows 100% uptime of Essence of the Red but no energy is gained according to the data in Resource Breakdown (and no change in DPS either).

I have not checked whether this is also the case for mana or rage.

Is this a known bug?

Best,
J.

**Comment by timhul** [comment]
Fixed in de59abe6a6ea62be2c8cd022915cbb4847dff9b5. The error was essentially a refactoring made quite a while ago so this has likely been broken since. The fix was to resolve what was essentially technical debt, wherein the previously mentioned refactoring never made it to the Vaelastraz buff.
