### ISSUE TITLE
Zandalarian Hero Medallion reduces DPS

### ISSUE THREAD

**Issue by Jinnai** [timhul/ClassicSim#159]
Using this trinket gives you minus DPS compared to not wearing a trinket at all. Tried with various combat lengths.

**Comment by timhul** [comment]
I am unable to reproduce this in the latest version. This trinket consistently gives around 1-2% damage increase depending on fight length and setup.

**Comment by Jinnai** [comment]
Okay, this seemed to occur in combination with Diamond Flask. I assume ZHM puts DF on CD which causes the result. This is probably correct behavior?

**Comment by timhul** [comment]
Trinket uses does incur trinket cooldowns so it is not possible to double stack them or other shenanigans, yes. That means if ZHM is a weaker trinket than DF but it has higher priority it could make the DF usage worse, which overall would be a DPS decrease.

I am closing this for now, feel free to open it if you find further information.
