### ISSUE TITLE
Warlock isn't working

### ISSUE THREAD

**Issue by beflew** [timhul/ClassicSim#161]
Hi, when I click the Warlock tab on the upper left corner, nothing happens. Is this a known issue?

**Comment by timhul** [comment]
Yes, although it is not an issue. Warlocks are not supported in the latest release, but as it happens I worked on them just yesterday so they'll be available in its first version (DS/Ruin SB spam) very soon.

Thanks for your report.

**Comment by timhul** [comment]
There is now a release available with initial support for warlocks.
