### ISSUE TITLE
[Suggestion] add Huge Thorium Battleaxe

### ISSUE THREAD

**Issue by Mizzajl** [timhul/ClassicSim#197]
made a fork with the Huge Thorium Battleaxe added:
https://github.com/timhul/ClassicSim/compare/master...Mizzajl:patch-1

**Comment by timhul** [comment]
Hi, please make a pull request for it!

**Comment by Mizzajl** [comment]
ok done, was still a little unsure how github works :)

**Comment by timhul** [comment]
Good job!
