### ISSUE TITLE
Build on Darwin fails due to not having <cmath> included

### ISSUE THREAD

**Issue by jokal2** [timhul/ClassicSim#20]
I'm guessing you wrote and build this regularly on Windows with cl. I don't know how you're getting `round`, `std::round` and `pow` in many of these files, but on Darwin the build fails outright for nearly every invocation of `round`.

The change was as simple as adding `#include <cmath>` to all those files, but I figured there might be something in the build system that does this that I'm not aware of as I don't know qmake or qt.

**Comment by timhul** [comment]
I've been using the builtin Qt Creator build system which does set up a few of the system includes. Using another build system is currently not supported, but it's something I've been wanting to do for a long time now. While making a quick attempt at it I did notice the same issues you are having now, that <cmath> or <math.h> is indeed missing.

Feel free to make a pull request that adds the necessary inclusions.

**Comment by jokal2** [comment]
> I've been using the builtin Qt Creator build system which does set up a few of the system includes. 

Yup, I just opened QtCreator and pushed build and the above was the result.

> While making a quick attempt at it I did notice the same issues you are having now, that or <math.h> is indeed missing.

What do you mean by this? You can't get it to build either?

**Comment by timhul** [comment]
> > While making a quick attempt at it I did notice the same issues you are having now, that or <math.h> is indeed missing.
> 
> What do you mean by this? You can't get it to build either?

I can build with the builtin Qt Creator build system, but since it is configured to use my system environment (which should be a no-no in larger projects) I happen to have a setup that works.

What I was trying to say is that when I've tried to set up other build systems in the past I did not succeed and saw the same errors you are reporting. I prioritized completing other tasks at the time and haven't looked into making other build systems work since.

**Comment by jokal2** [comment]
> What I was trying to say is that when I've tried to set up other build systems in the past I did not succeed and saw the same errors you are reporting.

What else were you trying to use? I know nothing about Qt, but doesn't the fact that you built this as a Qt app require the Qt build system?

**Comment by timhul** [comment]
> What else were you trying to use? 

This was almost a year ago at this point so I don't quite recall, but I've wanted to set up Bazel for a while now.

> I know nothing about Qt, but doesn't the fact that you built this as a Qt app require the Qt build system?

It is not a requirement, no, but qmake is pre-configured to generate appropriate makefiles for the Qt ecosystem so it is a time-saver. See for example [this Bazel project](https://github.com/justbuchanan/bazel_rules_qt) that sets up rules that generates build actions to build Qt applications.

**Comment by jokal2** [comment]
This should be fixed via the similar patch that went in for Linux.
