### ISSUE TITLE
Shadow oil on 2 weapons causes crash

### ISSUE THREAD

**Issue by guymanthethird** [timhul/ClassicSim#202]
Hello,

It appears that attempting to put shadow oil on two 1H weapons immediately causes a crash once the second is selected. It happened 100% of the times I've attempted to do so.

Best

**Comment by timhul** [comment]
Thanks for the report, have confirmed it does consistently cause a crash.

**Comment by timhul** [comment]
Fixed in 78bf4e7a71a48f208194440c33a3df892389c2f2.
