### ISSUE TITLE
How To

### ISSUE THREAD

**Issue by INFlNlTY** [timhul/ClassicSim#204]
First off, I would like to thank you for creating a simulation tool for Classic Wow!

Secondly, I'd like to say I'm not used to GitHub or coding in general, but I'm trying to get this working.

Afaik; I needed to download the following:
Qt Creator (5.11.3)
mingw (5.3.0)
Git LFS
LLVM
I already have python 3.7 installed

I also installed the following to help me along:
GitHub Desktop

I mainly get confused as I've never used Qt Creator before, and I may not be building in the correct order/ I may not have all that is required.

Is there anything I'm missing?
Is there a Discord I could go to for individualized help?
Thanks so much!

**Comment by yellowmia11** [comment]
I don't see anything missing on your list. Can you describe what you tried and what error you are getting?
You should basically:
- git clone the repository
- git lfs pull
- python3 DevTools/copy_to_debug.py
- edit the debug_location in build.config
- Import the project in QtCreator
- Build and Run
- Reformat before committing

I would really love some kind of chat/discord to discuss the development in addition to what's possible in github.

**Comment by INFlNlTY** [comment]
Thanks for the response. I wasn't able to get it to work, but I think I'll leave it alone for now. I wanted to add rotations for hunter spec to check things out; I'll get to it
