### ISSUE TITLE
Enhancement Shaman issues

### ISSUE THREAD

**Issue by Mizzajl** [timhul/ClassicSim#205]
Shaman can't use polearms
they don't get 1 AP per STR and AGI, they get +2 AP per STR and no AP for AGI.
I made a pull request for a fix, not sure if any other files need to be modified as well.

[Fix](https://github.com/timhul/ClassicSim/pull/201)

**Comment by timhul** [comment]
Thanks for the pull request. There is more work needed for Shaman, but for this issue the scope is complete with your pull request.
