### ISSUE TITLE
Darwin fails on `EquipmentDb::read_equipment_files` due to missing "equipment_paths.xml"

### ISSUE THREAD

**Issue by jokal2** [timhul/ClassicSim#21]
This file is right next to the source file in the source tree but obviously not in the built binary. I don't see a "package-all-xml-files-and-put-them-next-to-the-built-binary" step in the build, but this is the first time I've ever looked at qmake so I couldn't really tell.

**Comment by timhul** [comment]
Check out the https://github.com/timhul/ClassicSim/wiki#development-environment, and in particular the section regarding the development tool repo https://github.com/timhul/CSIMDevTools .

**Comment by jokal2** [comment]
Yup, this worked with a few modifications. Thanks!
