### ISSUE TITLE
2H Fury Simulation is bugged on white attack missing rate

### ISSUE THREAD

**Issue by Tom9888** [timhul/ClassicSim#218]
The simulation for 2H fury is not correct. according to the statistics after the simulation, the 2H fury has huge missing rate (more than 15%) .
For example, I used Orc to simulate the boss fight with 20/31/0 build on 2 hand fury. The weapon is 2 handed axe ( Drake Talon Cleaver). The gear hit rating is 6% capped. Only dodged attack from behind. According to the statistics, the 2 handed axe attack was treated as main hand attack which resulted in 17.18% missing rate.
Not sure if this was intended for simulation. If it was not intended, I believe it is a bug.

**Comment by Tom9888** [comment]
![image](https://user-images.githubusercontent.com/62989165/78122232-0ee6f480-743f-11ea-930e-eed847a694ed.png)

**Comment by veluria** [comment]
White hits are  – as they should be – at the top of that list (Mainhand Attack). And they didn't miss. Pretty sure that entry is about the weapon's proc. As to why it's being listed as miss and whether it can miss, I don't know, but as it does really low damage, it shouldn't matter much.

**Comment by Tom9888** [comment]
After more simulation with Proc weapons including Thunderfury. I believe this is working as intended. The proc damage miss (or resist) was set at almost fixed percentage. Almost no impact regardless increase on hit rating (both physical and spell) or not.
