### ISSUE TITLE
Hunter and Elixir of the Mongoose 

### ISSUE THREAD

**Issue by Browender** [timhul/ClassicSim#221]
Launched a sim on my Dwarf hunter with lot of buffs and Elixir of the mongoose.
Launched the same sim with Elixir of Greater Agility and got the same result.

Tried with Elf hunter -> same issue
Tried with all horde race -> same issue
Tried with all other physical damage classe -> no issue
Tried with naked  (only weapon) hunter -> same issue
Tried with no talent -> same issue
Tried with Ground Scorpok Assay vs Elixir of the Mongoose -> same results

It's seem's that the +2% crit from Mongoose is not taken into account.

**Comment by timhul** [comment]
Elixir of the Mongoose only affected melee crit, but it was fixed in 4f4fc4872f72db8a102296ae5fc589ec11c2a071 by @yellowmia11. Thanks for the report!
