### ISSUE TITLE
Hunter's crit stat weight

### ISSUE THREAD

**Issue by Browender** [timhul/ClassicSim#222]
Launched a 100 000 iterations full sim for a hunter with +10 agi/+1% hit/+1%crit Scale factors and got negative Abs. value for 1% crit chance very often or very low value (1<)

DPS value was about 675 DPS.

Unequipped Blackhand's Breadth and relauched the full sim and got about 665 DPS so 2% crit -> 10 DPS

Perhap's this issue is linked with Elixir of the Mongoose issue for hunter.

**Comment by yellowmia11** [comment]
I tested this. The results are: 
There is a bug in the Mongoose code and in the Scale Factors for the Crit Chance.
Both apply the crit chance only to melee attacks, but not to ranged attacks.
Should be a simple fix.

**Comment by timhul** [comment]
Thanks for the report. Fixed in 4f4fc4872f72db8a102296ae5fc589ec11c2a071.
