### ISSUE TITLE
Mage armor mana regeneration missing

### ISSUE THREAD

**Issue by f90** [timhul/ClassicSim#237]
With the mage armor buff, the mage gets 30% of the normal mana regeneration while casting. I don't see this being applied anywhere in the code, so currently the simulator often mistakenly thinks the mage is out of mana, overvaluing the mp5 stat.

The 15% from the arcane talent does get applied though, so it should be easy to fix this since this mechanic is already modelled in code.

Maybe this can be included in the initialisation of the Mage class so it's set to 0.3 as default value, with talent addition/removal then increasing/decreasing this?

**Comment by timhul** [comment]
Thanks for the report. Mage Armor should be implemented as a spell that applies the described buff. Your suggested solution is a possible quick interim solution.

**Comment by f90** [comment]
This is maybe unrelated but I wanted to spend a bit of time to implement this, but cannot get it to compile using QtCreator and MinGW on Windows 10 64bit. Is there a way to contact you @timhul /more in-depth help on how to get started contributing? I followed the dev information on the Wiki here but still no luck

**Comment by f90** [comment]
This can be closed as soon as pull request #254 is approved :)
