### ISSUE TITLE
Mage \\ different fight length dps

### ISSUE THREAD

**Issue by Robnroll** [timhul/ClassicSim#240]
Hey,
i'm not completly sure if thats an issue or if i just got something wrong but i noticed that the length of the fight has no impact at all at my dps.
I'm siming an arcane frost mage and just in theory i would assume that a shorter fight should have higher dps. For example because of the effect of arcane power beeing active for a higher percentage of the fights length and no mana problems. In a fight with 600sec length the use of evocation or manapots etc might be necessary which should result as well in a lower dps value overall. I'm not really deep into the mechanics so maybe i just got something wrong. Just wanted to share my thoughts.
Keep up the good work, really love your tool!
Rob

**Comment by veluria** [comment]
Did you confirm the value by hitting enter after typing? Otherwise it will not be changed. That's easy to miss. DPS should definitely be higher.

**Comment by Robnroll** [comment]
Actually i didn't, sorry! Tried it now with confirming and the dps is changing. Thanks for you help!

**Comment by timhul** [comment]
Glad you found the cause of the issue.
