### ISSUE TITLE
Buffs are not calculated correct

### ISSUE THREAD

**Issue by violatorno** [timhul/ClassicSim#276]
760+ dps in a 5 minutes encounter?
The potion/buff/debuff  calculations are not calculated correct, just try it yourself and you see.

![Annotation 2020-05-11 032510a](https://user-images.githubusercontent.com/58947457/81516190-5febe180-9337-11ea-9554-2b439a717b45.png)
![Annotation 2020-05-11 032510b](https://user-images.githubusercontent.com/58947457/81516199-637f6880-9337-11ea-9724-ccfc072c9895.png)
![Annotation 2020-05-11 032510c](https://user-images.githubusercontent.com/58947457/81516202-667a5900-9337-11ea-8da2-fa6c5d8541ae.png)
![Annotation 2020-05-11 032510d](https://user-images.githubusercontent.com/58947457/81516205-67ab8600-9337-11ea-8f8d-9fbe09e5012d.png)

**Comment by violatorno** [comment]
Also, when changing armor value to 5600 on sim settings dps drops by only 1

**Comment by yellowmia11** [comment]
Did you press enter after typing in each value in the settings?

**Comment by violatorno** [comment]
Screenshot is with default values.
Yes, I did press enter when changing armor, seems it missed thou, since when making 100% sure that the change in armor value is applied dps drops to more normal values.
