### ISSUE TITLE
ZG items not showing

### ISSUE THREAD

**Issue by DupKan** [timhul/ClassicSim#278]
The ZG set pieces and, at least from what I've searched, plate off-pieces from ZG, don't show up in the Sim for selecting gear.

**Comment by jokal2** [comment]
Yup. They are added the first time somebody who wants it decides to add it. It's pretty easy to do so feel free to add whatever you'd like. [Here's an example.](https://github.com/timhul/ClassicSim/pull/291/commits/de626afff689f1c2af54b0440003132c6e5aaff1)
