### ISSUE TITLE
Rogue stat values str>ap

### ISSUE THREAD

**Issue by Kaladryn** [timhul/ClassicSim#280]
Stat weights for rogues are showing Strength is worth 20% more than Attack Power WITHOUT kings or zg buff. This doesn't seem possible.

**Comment by jokal2** [comment]
I'd say the stat weights are merely guidance and not real weights. The variance between sim runs is way too high for those values to be definitive. Maybe jump the `Iterations` to 10,000,000 or something and go get lunch and use those values instead. But the default value iterations are way too low for completely meaningful stat weights.
