### ISSUE TITLE
Buff Selection

### ISSUE THREAD

**Issue by Zwoxlol** [timhul/ClassicSim#282]
So i wanted to select the Buffs we have and compare a bit how they increase the Damage.
The problem is when i selected already this buffs 

![image](https://user-images.githubusercontent.com/65707907/82542196-debff600-9b51-11ea-9abd-173cddf30500.png)

and wanna add "Arcane Intellect" this happens.

![image](https://user-images.githubusercontent.com/65707907/82542232-f0090280-9b51-11ea-8991-6f0bf861e59f.png)

Its selects for some reason tons of other Buffs aswell.

**Comment by veluria** [comment]
Can't reproduce this. How are you selecting multiple buffs? Just holding ctrl?

**Comment by Zwoxlol** [comment]
> Can't reproduce this. How are you selecting multiple buffs? Just holding ctrl?

Shift and then a Mouse Button

**Comment by veluria** [comment]
You should use ctrl + mouse for selecting single buffs, not shift.
