### ISSUE TITLE
Talents do not switch to new class.

### ISSUE THREAD

**Issue by developforapple** [timhul/ClassicSim#305]
After clicking the class switch, the talent panel remains in the previous class instead of the current one.
Compile using QT 5.14.2 with the latest code.
The bug seems to be due to a recent commit: https://github.com/timhul/ClassicSim/commit/674ddbf1119ee38650a57b925e951e034112478b#r39887454
The "emit classChanged();" was removed and the signal for class change was not emit.

**Comment by veluria** [comment]
Thanks for the report. :+1:
