### ISSUE TITLE
Items missing

### ISSUE THREAD

**Issue by VulpesHD** [timhul/ClassicSim#311]
Hey,

some items are missing from the program:
https://classic.wowhead.com/item=21498/qiraji-sacrificial-dagger
https://classic.wowhead.com/item=19836/zandalar-madcaps-bracers
https://classic.wowhead.com/item=19954/renatakis-charm-of-trickery

Please add them in the new update.

Thank you!

**Comment by veluria** [comment]
Added this set and even the trinket's use! Not sure if there would have been an easier way to make the trinket work, but this should work fine.
