### ISSUE TITLE
Shadowcraft 6-set should not proc on abilities (yellow hits)

### ISSUE THREAD

**Issue by sosz** [timhul/ClassicSim#314]
As far as we know, Shadowcraft only procs on white hits: https://docs.google.com/spreadsheets/d/1Z62Mn9ZUsAjelbyDnWNPrDBGHQhLXRwW6YFRsV2fVgk/edit#gid=1147611224
(from Rogue discord).

It looks like Shadowcraft is set to proc on yellows:
https://github.com/timhul/ClassicSim/blob/569a56a99eb3ac34292d2c89a7a6965c144bc8d0/Equipment/SetBonusControl.cpp#L61-L63

Also, is the `0.035` proc chance a static chance? It should be about ~1 PPM for MH, and ~1 PPM for OH, so proc chance needs to be adjusted for weapon speed. Not sure if that is happening somewhere else in the code

**Comment by veluria** [comment]
I went ahead and removed the yellow hit proc. I can't do much about the fixed proc rate though, sorry. With 1 PPM, it's not that far off though, even for different weapon speeds.
