### ISSUE TITLE
Warrior Rotations: Bloodrage

### ISSUE THREAD

**Issue by LawrenceMz** [timhul/ClassicSim#335]
Bloodrage is only cast before the start of the fight (precombat_actions), however shouldn't it be on the priority list?
Similar to how it happens with Berserker Rage.

`
    <cast_if name="Bloodrage">
        resource "Rage" less 50
    </cast_if>
`

**Comment by jokal2** [comment]
Yea, that makes sense. Feel free to play around with the xml files for the rotations. More contributors are always welcome!
