### ISSUE TITLE
Soulstring DPS and other Ranged Weapons

### ISSUE THREAD

**Issue by valepu** [timhul/ClassicSim#340]
Hello,
I have noticed that Soulstring's DPS is incorrect, the tooltip on classic wowhead says 50.86 while classicsim lists it at 60.7 which is even higher than Nerubian Slavemaker https://classic.wowhead.com/item=22811/soulstring and when i equip it and run the sim i get more DPS with Soulstring than with Nerubian Slavemaker, which shouldn't happen

Then, today i have downloaded the latest released version (Jul 12th) and I have noticed 2 differences with the version i used up until now (May 3rd)
1. Rhok does more DPS than Ashjre'thul (it should do less in theory), in the previous version Ashjre'thul was doing a lot more DPS than Rhok
2. In the May 3rd version Ashjre'thul was doing more DPS than Nerubian Slavemaker, now it should be correct
3. Huhuran's Stinger does slightly less DPS than Rhok, in the previous version was doing slightly more. I can't confirm or deny this one because i haven't tested on live but in theory it should be correct now (i have a Huhuran's Stinger but haven't got a scope yet, I shall test it as soon as possible)

**Comment by veluria** [comment]
There's most certainly a bug with Hunter DPS and the results are not reliable. Has been like this forever, unfortunately. See als #206

**Comment by valepu** [comment]
I was just reading that issue. Before posting this one i searched "Soulstring" to see if someone else reported it but then after posting i tried searching for Ashjre'thul and found the issue. Thanks

There's still the Soulstring part which seems more straightforward to fix, at least to my non-expert eye

**Comment by veluria** [comment]
If you want, you can download the updated XML and put it into your ClassicSim folder under `Equipment/EquipmentDb/Weapons`.
