### ISSUE TITLE
Hunter base attack power

### ISSUE THREAD

**Issue by valepu** [timhul/ClassicSim#342]
Hello,
I have noticed that the hunter's starting ranged attack power is set at 160 but, according to my calculation on a real toon in game, it should be 100.

There is something weird going on because most sites report classic hunters RAP to be (level * 2) + (agi * 2) - 10 https://classic-wow.fandom.com/wiki/Attack_Power_formulas . That would put the hunter's base RAP at lvl 60 to be 110 but i couldn't get such a value on my hunter. I made a fresh new hunter and even in that case the formula was wrong (lvl 1 hunter with 28 agi had 38 RAP, but according to the formula it should've had 1 * 2 + (28 * 2) - 10 = 2 + 56 - 10 = 48 RAP). 
But i guess this is not that relevant for the scope of classicsim.

I'm attaching some screenshots of my hunters RAP (I'm using the classic stats addon but after making the screenshots i checked with the addon disabled and the values were correct)

![lvl1hunter](https://user-images.githubusercontent.com/5619832/93597682-bdfe9480-f9bb-11ea-8e17-71cb2babe283.PNG)
![lvl60hunter](https://user-images.githubusercontent.com/5619832/93597687-bfc85800-f9bb-11ea-90a8-74890fb29c27.PNG)

**Comment by veluria** [comment]
So this should be 100, right?

https://github.com/timhul/ClassicSim/blob/5df9bc901a0019fd8647420eb6838dfd294decaa/Class/Hunter/Hunter.cpp#L37

**Comment by valepu** [comment]
Yes that should fix it, i can make a pull request myself if you want but was looking for confirmation first. Thanks

**Comment by veluria** [comment]
Confirmed.
