### ISSUE TITLE
Missing Demonshear

### ISSUE THREAD

**Issue by veluria** [timhul/ClassicSim#35]
https://classic.wowhead.com/item=13348/demonshear

I'd create a pull request myself, but I have no idea about the proc rate.

**Comment by timhul** [comment]
> https://classic.wowhead.com/item=13348/demonshear
> 
> I'd create a pull request myself, but I have no idea about the proc rate.

I would accept a pull request with an unknown proc rate and we can change it after more data is revealed.

**Comment by veluria** [comment]
Just collecting some other items to add that are missing:

https://classic.wowhead.com/item=18420/bonecrusher
https://classic.wowhead.com/item=13400/vambraces-of-the-sadist

**Comment by jokal2** [comment]
[Handcrafted Mastersmith Leggings were added](https://github.com/timhul/ClassicSim/pull/29). Implementation for those other items could be done via just looking at this PR as an example.

**Comment by veluria** [comment]
Fixed by #47.
