### ISSUE TITLE
Aimed Shot cast speed should be unaffected by quiver ranged attack speed increase.

### ISSUE THREAD

**Issue by MelvinKellner** [timhul/ClassicSim#36]
As far as i can tell quiver currently affects Aimed Shot casting speed, this messes with the rotation and make faster ranged weapons give better results than they should.

**Comment by timhul** [comment]
Aimed Shot casting speed is indeed currently reduced by ranged attack speed increases, will look into this. Thanks for the report.

**Comment by timhul** [comment]
Fixed in ab5c6eca076c4fedb2e194e5e14bb1975b4e5731.
