### ISSUE TITLE
missing some items

### ISSUE THREAD

**Issue by sylekta** [timhul/ClassicSim#37]
gutgore ripper and corehound tooth are missing from daggers

**Comment by jokal2** [comment]
Adding items is pretty simple. Take a look at some of the most recent closed pull requests. I also have an open PR for CHT, I just need to find the icon for it.

**Comment by sylekta** [comment]
So would i just insert into 1h daggers xml

<melee_weapon id="17071" phase="1">
		<info name="Gutgore Ripper" type="DAGGER" slot="1H" unique="yes" req_lvl="60" item_lvl="70" quality="EPIC" boe="no" icon="Inv_weapon_shortblade_18.png"/>
		<dmg_range min="63" max="119" speed="1.8"/>
		<stats>
			
		</stats>
		<source>
			Drops from Garr in Molten Core.
		</source>
	</melee_weapon>

and not bother with the proc cause it doesnt add fuck all anyway?

**Comment by timhul** [comment]
> So would i just insert into 1h daggers xml
>  ...
> and not bother with the proc cause it doesnt add fuck all anyway?

Sure, you can also just add the tooltip for the proc as a <special_equip_effect> element which only adds it to the tooltip and has no actual effect.

**Comment by timhul** [comment]
Added in 3996c945843d8d52b7fa20660420d288e100e385.
