### ISSUE TITLE
License incompatibilities

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [timhul/ClassicSim#374]
LGPL paragraph 7 states that:
`If the Program as you received it, or any part of it, contains a notice stating that it is governed by this License along with a term that is a further restriction, you may remove that term.`

so it will invalidate the additional restricting license terms found at the top
```
Be free of charge
Only be provided as a digital product
Be restricted to the ®World of Warcraft IP
Be free of advertisements
```

and maybe this term

`This project ("ClassicSim") adheres to the "Blizzard Developer API Terms of Use", which can be found at https://dev.battle.net/policy .`

**Comment by timhul** [comment]
Thanks for the notification. LGPL does **not** state this, but GPL does.

 I do think it is confusing that the license include a copy of an unused GPL license however, which could be removed to remedy the confusion. Note that the license text explicitly states it adheres to LGPL and not GPL though.

Closing this as I don't think there are any license incompatibilities with LGPL.
