### ISSUE TITLE
Character stats doesn't match in game stats

### ISSUE THREAD

**Issue by Yawei-Li** [timhul/ClassicSim#42]
Hi! Thank you for this awesome project!
I'm using the lateset released version(191007), testing human rogue.
Without any gear or buff, my stats shown in Classicsim are:
STR 81
AGI 133
STA 81
INT 35
SPI 50
AP: 374
Crit: 4.59%

In game, they are:
80/130/80/35/52
310AP, 5.68%Crit.

There seem to be an extra 60AP after extra stats, and less than 1% missing crit.

**Comment by timhul** [comment]
Thanks for the report!

The base stats have not yet been updated to Classic values, and it affects all classes.

**Comment by timhul** [comment]
Rogue stats are updated a bit in 8388509db4b42de8c3de016eb85d11c2fc431ea7, although I expect there to still be slight deviations due to race base stats differences.
