### ISSUE TITLE
Allow higher simulation iterations.

### ISSUE THREAD

**Issue by ssateneth** [timhul/ClassicSim#49]
I have a high power computer that can burn through iterations super fast. Also, 10k iterations still introduces a lot of error in stat weights. Can I set a higher number please, like 100000 or 1 million? I'm fine with waiting for a long sim to complete, I just want more reliable stat weights.

Also looking forward to custom combat rotations.

**Comment by timhul** [comment]
> Also looking forward to custom combat rotations.

Custom player rotations? Those are already available but you have to edit the .xml files, they are not possible to edit via the GUI.

If not, please clarify what it is you want.

**Comment by ssateneth** [comment]
Ah I see the XML files, I'll look into them for editing. Thanks.

**Comment by timhul** [comment]
It is possible to sim higher number of iterations in 3c75467183d0e70e9ce055f1f924ea5c8a4e8783.

Thanks for the report!

**Comment by ssateneth** [comment]
Maybe I misunderstood the iterations. I was under the impression that increasing the iterations would increase the precision of stat weights. However, it seems that the stat weights iterations is static, so I still get a huge amount of variation in stat weights between each sim, even at 1M iterations. Is it possible to change the amount of iterations done for stat weight calculations? Thank you for developing this helpful tool.

**Comment by ssateneth** [comment]
In fact, the iterations setting in both full simulation and quick simulation seem to do NOTHING. If I put 100 or 1 000 000, it doesnt matter. The speed is exactly the same, and statistics -> internal engine does not reflect additional event sthat should occur from more iterations. Seems there is a bigger problem here.
