### ISSUE TITLE
felstriker proc chance is incorrect, and its proc need to be confirmed.

### ISSUE THREAD

**Issue by meteorhill** [timhul/ClassicSim#52]
Hi, 

Very nice tool, really good job.

But i think felstriker's PPM should be 1 in vanilla. And Flurry Axe's PPM is 1.85.

After i adjusted  the proc chance i simulated the gear with felstriker,but it was still way too strong.

So i doubt that its proc didnt calculate the chances of dodge and glancing blows. 

Check the Proc Rate sheet in the attachment, it might help.

Please let me know if i was wrong.

Cheers.

[DPSWarrior_Classic (1).xlsx](https://github.com/timhul/ClassicSim/files/3791210/DPSWarrior_Classic.1.xlsx)

**Comment by timhul** [comment]
Hi,

Proc rates updated accordingly in 871d2e190614201191c15004819ed1981d8f354c.

> 
> So i doubt that its proc didnt calculate the chances of dodge and glancing blows.
> 

I am unsure what you are trying to say here. Felstriker can currently proc from successful attacks made by its weapon slot (so if placed in MH only MH attacks procs it). Glances are successful hits and thus can proc Felstriker, whereas dodge/miss/parry is not and will not proc Felstriker. 

Please clarify if I have misunderstood something.

**Comment by meteorhill** [comment]
Hello, Thanks for reply. The proc of felstriker, “All attacks are guaranteed to land and will be critical strikes for the next 3 sec”. When I have already proc this dagger, it gives me 100%crit for sure and maybe also 100%hit. But it won’t remove the dodges,glances,blocks..etc.  Yellow attack can still be dodged, and white attack can be dodged and glanced during the proc? I made a lot of simulations about felstriker with classicSim. The results showed that felstriker was better than most of weapons till phase 5. I just not sure how the proc works on classicSim. So that I’m not sure for the reliability of the sim results. ------------------ 原始邮件 ------------------
发件人: "Tim Hultman"<notifications@github.com>
发送时间: 2019年11月3日(星期天) 晚上7:46
收件人: "timhul/ClassicSim"<ClassicSim@noreply.github.com>;
抄送: "meteorhill"<meteorhill@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [timhul/ClassicSim] felstriker proc chance is incorrect, and itsproc need to be confirmed. (#52)



Hi,
 
Proc rates updated accordingly in 871d2e1.
  
So i doubt that its proc didnt calculate the chances of dodge and glancing blows.
  
I am unsure what you are trying to say here. Felstriker can currently proc from successful attacks made by its weapon slot (so if placed in MH only MH attacks procs it). Glances are successful hits and thus can proc Felstriker, whereas dodge/miss/parry is not and will not proc Felstriker.
 
Please clarify if I have misunderstood something.
 
&mdash;

**Comment by timhul** [comment]
> When I have already proc this dagger, it gives me 100%crit for sure and maybe also 100%hit. But it won’t remove the dodges,glances,blocks..etc. Yellow attack can still be dodged, and white attack can be dodged and glanced during the proc?

Felstriker in its current implementation does indeed give 100% crit and 100% hit for the duration of its proc,  [as found here](https://github.com/timhul/ClassicSim/blob/master/Class/Common/Buffs/FelstrikerBuff.cpp). It does not modify the rate of glancings or dodge/parry so those will still occur during the buff. However, in earlier releases (before August) it did modify glancing blow tables, are you sure you are using a newer release?

I'm curious what sort of setup you are using where the sim is suggesting Felstriker is that powerful. Rogue/Warrior?

**Comment by meteorhill** [comment]
Hi, Tim


Really appreciate for your helpful reply.&nbsp; After i simulated&nbsp;my Warrior gear in the last release with the updated proc chance, i found that Core Hound Tooth was way better than Felstriker and it's convincing.&nbsp;


And also a new question was made.&nbsp; I changed the proc of&nbsp;Flurry Axe in 1hAxes.xml like this&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<special_equip_effect&gt;
			Chance on hit: Grants 10 extra attack on your next swing.
		</special_equip_effect&gt;
or i just removed this codes.&nbsp;There was no corresponding change in the simulation results. I didnt test other NextSwingWeapons.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tim Hultman"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月4日(星期一) 凌晨4:57
收件人:&nbsp;"timhul/ClassicSim"<ClassicSim@noreply.github.com&gt;;
抄送:&nbsp;"[淘宝网]"<meteorhill@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [timhul/ClassicSim] felstriker proc chance is incorrect, and its proc need to be confirmed. (#52)



 
When I have already proc this dagger, it gives me 100%crit for sure and maybe also 100%hit. But it won’t remove the dodges,glances,blocks..etc. Yellow attack can still be dodged, and white attack can be dodged and glanced during the proc?
  
Felstriker in its current implementation does indeed give 100% crit and 100% hit for the duration of its proc,  as found here. It does not modify the rate of glancings or dodge/parry so those will still occur during the buff. However, in earlier releases (before August) it did modify glancing blow tables, are you sure you are using a newer release?
 
I'm curious what sort of setup you are using where the sim is suggesting Felstriker is that powerful. Rogue/Warrior?

**Comment by timhul** [comment]
You're welcome and thanks for the report. I'll be closing this issue as everything in this context seems resolved.
