### ISSUE TITLE
Paladin`s Strength & Agility error

### ISSUE THREAD

**Issue by newtrafford** [timhul/ClassicSim#54]
Hi,
Thanks to the tool!
And I find some problems in Release191027, in the simulator the stats weighting for Paladins is still 1Str=1AP and 1Agi=1AP
Actually it is 1Str=2AP, 1Agi=0AP (like Warrior)

and can`t find ‘Judgement’ in the Damage Breakdown, although it exists in the Rotation

Looking forward to fix these problems.

**Comment by timhul** [comment]
Hi, thanks for the report!

Paladin stats were fixed in https://github.com/timhul/ClassicSim/pull/48 which is due to be released, please make a separate issue for Judgement where you list what seals were used in the rotation, alternatively which rotation you used if you didn't' modify it.
