### ISSUE TITLE
"Allow higher simulation iterations" not implemented correctly.

### ISSUE THREAD

**Issue by ssateneth** [timhul/ClassicSim#61]
Maybe I misunderstood the iterations. I was under the impression that increasing the iterations would increase the precision of stat weights. However, it seems that the stat weights iterations is static, so I still get a huge amount of variation in stat weights between each sim, even at 1M iterations. Is it possible to change the amount of iterations done for stat weight calculations? 

After further testing, the iterations setting in both full simulation and quick simulation seem to do NOTHING. If I put 100 or 1 000 000, it doesnt matter. The speed of the sim is exactly the same, and statistics -> internal engine does not reflect additional events that should occur from more iterations. Seems there is a bigger problem here and needs another look at it.

**Comment by timhul** [comment]
Will have another go, it definitely increased the iterations on my end when I was developing it so have to check deeper.

I apologize for the delay in responding, I've been very busy the last few days.

**Comment by Gratchoof** [comment]
After typing in a new number of iterations be sure to hit <Enter> before running the full sim.

If you don't, then it still picks up the old number.

**Comment by ssateneth** [comment]
Aha, that seems to be the missing link. I thought you only had to put in the new number and thats it. I didnt know you had to press enter too. There wasn't any hint to tell you to push enter after putting ina  new number

**Comment by ssateneth** [comment]
Can close the issue now. I propose saving the contents of the iterations field (or any other field) when the contents is updated and not just when the enter key is pressed.
