### ISSUE TITLE
Cannot find Songstone of Ironforge in rings.xml

### ISSUE THREAD

**Issue by bobjiang6** [timhul/ClassicSim#67]
I used the version from the latest release and i chose to simulate my mage.
But i could not find the ring 'Songstone of Ironforge'. The item id is 12543, which can be obtained from a quest from Princess Moira.
The only similar ring in rings.xml is Magni's Will, whose item id is 12548.
I do not know whether the mutex function is working correctly, but i got no spell damage bonus when i choose the ring.
Thank you very much for this issue

**Comment by veluria** [comment]
I'm adding it in #63. :) Should be available whenever @timhul puts out the next release.

**Comment by timhul** [comment]
This ring was indeed added in 33f10b88696f972db441ec8285997d2f6b4fbd8a and will be in the next release the upcoming days.

Thanks for the report!
