### ISSUE TITLE
Support random affixes on items

### ISSUE THREAD

**Issue by timhul** [timhul/ClassicSim#7]
# Background

While leveling the main attire of characters is going to be of green quality for the large majority of the playerbase. These items can often spawn with random affixes. The available set of affixes depends on patch (e.g. +spell damage/+healing which was not available in 1.0.0), and the stat values depend on item level and slot. Because they are ubiquitous for players, especially during leveling, the support for them needs to be smooth.

Note: there are a handful of very powerful items (different +spell damage/healing items) that could explicitly be added without the general support for random affixes. This issue aims to solve the general case of random affix items, which includes these powerful endgame items.

Note: make the assumption initially that all affixes are available in the first content phase.

# Expected implementation

## XML representation

Items that have a set of random affixes tied to them should be marked as such in the xml-files. The easiest thing is to let each item that has a set of random affixes name both affix name and the stat value changes they bring. [ItemFileReader](https://github.com/timhul/ClassicSim/blob/master/Equipment/EquipmentDb/ItemFileReader.cpp) (and Weapon) need to be able to parse these affixes.

`<RANDOM_AFFIXES> <RANDOM_AFFIX name="of the Moon" description="+Sta/+Int"></RANDOM_AFFIX>
<RANDOM_AFFIXES>`

## GUI representation

When selecting an item with random affixes there needs to be some dropdown from a model that displays the available random affixes for the item. Exactly where this dropdown should be placed must be investigated after the criteria how intuitive it is to use versus how difficult it is to implement.

# Definition of Done

* Possible to select items with random affixes and be able to select a specific affix.

**Comment by Skygg3** [comment]
I'm working on that issue right now and before I go any further, I'd like to know what you think about it.

I have found a list of all possible affixes (https://wowwiki.fandom.com/wiki/SuffixId?oldid=204430) and I plan to add an XML (I don't know where to put it right now) that will contain these data and will look like this :

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<random_affixes>
	<random_affix id="1416" phase="1">
		<info name="of Fire Resistance" />
		<stats>
			<stat type="FIRE_RESISTANCE" value="18"/>
		</stats>
	</random_affix>
</random_affixes>
```

This way, I think it will be easier to add random affixes to items with the simple addition of a list of affix IDs. This allows us to avoid having to add, for each item, the name, description and stats values of all possible affixes. An item with random affixes will look like this:

```xml
<item id="18295" phase="2">
	<info name="Phasing Boots" type="CLOTH" slot="BOOTS" unique="no" req_lvl="50" item_lvl="55" quality="RARE" boe="yes" icon="Inv_boots_06.png"/>
	<stats>
		<stat type="ARMOR" value="54"/>
		<stat type="INTELLECT" value="6"/>
		<stat type="STAMINA" value="6"/>
	</stats>
	<random_affixes>
		<affix id="1416"/>
		<affix id="1508"/>
		<affix id="1324"/>
		<affix id="1370"/>
		<affix id="1462"/>
	</random_affixes>
	<source>
		Drops from Phase Lasher in Dire Maul.
	</source>
</item>
```

As for the GUI representation, I'm thinking about adding "\<Random enchantment>" at the end of the name of the items with random affixes as well as a popup with all the possible affixes as shown in the image below.
This behaviour is relatively similar to the one on wowhead : https://classic.wowhead.com/gear-planner/mage/troll

![](https://i.imgur.com/AlibNqi.png)

Tell me if you think there's something wrong with this implementation.

**Comment by timhul** [comment]
I think your suggestion sounds good. You *might* encounter issues placing models on top of another model that uses a ScrollView (affix model on top of item model), but hopefully not. There is a reason there are no tooltips when hovering over items in the item model (I found no way to get mouse position, or really any element position, and therefore anchor a tooltip in a ScrollView).

If nothing else you can place the affix model somewhere else, like connected to the equipment slot like tooltips are.
