### ISSUE TITLE
Add Skull Splitting Crossbow

### ISSUE THREAD

**Issue by ssateneth** [timhul/ClassicSim#77]
Please add Skull Splitting Crossbow.

Rare BOE
Crossbow
52 - 79 Damage       Speed 2.60
(25.2 damage per second)
+3 Strength
Equip: +14 Attack Power.
Requires Level 43
Item Level: 48

**Comment by timhul** [comment]
Added in c835b6dfc380f293eac52626092aa708f6a96322.
