### ISSUE TITLE
"total damage" overflow to negative on high iteration runs

### ISSUE THREAD

**Issue by ssateneth** [timhul/ClassicSim#84]
With iterations as low as 40000, I am getting overflows of "total damage" to negative, assumingly because you are working with 32-bit signed ints. is it possible to set it up for larger numbers? this might explain why sometimes, my DPS in the top right doesn't make sense, like 0.26 dps or 32.12 dps, o some low number, when running high iteration runs with scale factors enabled.

https://i.imgur.com/AcEOWJ7.png

**Comment by timhul** [comment]
I was a bit afraid it would happen; using 32 bit ints which will have to be replaced. Thanks for the report!

**Comment by timhul** [comment]
A test run using Naxx warrior with max iterations before and after referenced commit above showed that the damage overflow was resolved in said commit.

Thanks for your report, and thanks to Skygg3 for delivering a fix!
