### ISSUE TITLE
Rogue talent Lethality damage calculation

### ISSUE THREAD

**Issue by sosz** [timhul/ClassicSim#87]
I see that currently the Rogue talent Lethality increases your crit damage using the formula `damage * crit_modifier * lethality`, causing your crits to become 30% stronger when investing 5/5 points into the talent.

The wording of the talent, as well as many mentions in guides suggest that Lethality simply increases your crit modifier (from 200% to 230%), which is a lot weaker: `damage * (crit_modifier + lethality)`

I've been Googling a bit without a definitive answer...

**Comment by timhul** [comment]
I am fairly sure you are correct that it should work like Impale, which is additive like the nerfed example you provided above.

**Comment by timhul** [comment]
Changed to be additive in 32b8e4f0edcc9d8be2ad3c91bdcd8b1a0a16c1d1.
