### ISSUE TITLE
Rogue's Shadowcraft (6) set bonus adds 30 agility?

### ISSUE THREAD

**Issue by sosz** [timhul/ClassicSim#88]
https://github.com/timhul/ClassicSim/blob/99d073358854b00002b2433738260aba853a90f3/Equipment/EquipmentDb/set_bonuses.xml#L118-L120

The above seems incorrect, it shouldn't add 30 agility

**Comment by timhul** [comment]
Hi, this was added as a temporary stopgap measure until the proc was implemented. Removed it now in 35723eeb297d7ebd3fd76aa6997ac5ec72e96329. Thanks for the report!
