### ISSUE TITLE
Proc of MH Mace "Empyrean Demolisher" was too high

### ISSUE THREAD

**Issue by jezecheng** [timhul/ClassicSim#91]
Hi Tim,

Per tested in "Desire Maul North", a ghost mob(level 60) which would not hit back and can be considered as a nice test target. it was indicating that 69 times of buff Proced from 1543 hit. 
https://classic.warcraftlogs.com/reports/Wh14c2dBLv6fCyQk#boss=-3&difficulty=0&type=auras&source=3
https://classic.warcraftlogs.com/reports/Wh14c2dBLv6fCyQk#boss=-3&difficulty=0&type=damage-done&source=3
This test was done by classic wow v1.13.2.

According to the formula
![image](https://user-images.githubusercontent.com/23181126/71456104-d2b64f00-27d2-11ea-9ed1-442f05ae7f73.png)
p-sample = 69/1543
n = 1543
Z(0.005) = 2.58
Z(0.025) = 1.96
Z(0.05) = 1.64

The real Proc of this weapon can be 
90% within range 3.78%-5.6%
95% within range 3.61% - 5.77%
99% within range 3.27%-6.11%

It's highly suspicious that the real PPM of this weapon in classic wow has been adjusted to 1, equals Proc of 4.666667%. (in the test which contains 1543 hit it was 4.69%) instead of 7%(currently in XML)

As it's a hot discussion regarding the scalability of this special Weapon, please consider to update the XML file to improve precision of simulation result.

BR
Jeze

**Comment by timhul** [comment]
Thanks for the detailed report. Updated accordingly in 8a125861b950c11d4d599406cbe2bfab287be123.
